FROM node:24-alpine

WORKDIR /app-dev

RUN apk add --no-cache redis

COPY package*.json .
COPY tsconfig.json .

RUN npm install

COPY . .

RUN sed -i 's/\r$//' ./docker/dev/docker-entrypoint.sh

RUN chmod +x ./docker/dev/docker-entrypoint.sh

EXPOSE 8000

ENTRYPOINT ["./docker/dev/docker-entrypoint.sh"]
