FROM node:24-alpine AS runner

WORKDIR /app-test

RUN apk add --no-cache redis

COPY package*.json .
COPY tsconfig.json .

RUN npm install

COPY . .

RUN sed -i 's/\r$//' ./docker/test/docker-entrypoint.sh

RUN chmod +x ./docker/test/docker-entrypoint.sh

EXPOSE 8000

ENTRYPOINT ["./docker/test/docker-entrypoint.sh"]
