FROM node:24-alpine AS runner

WORKDIR /app-test

COPY package*.json .
COPY tsconfig.json .

RUN npm install

COPY . .

RUN chmod +x ./docker/test/docker-entrypoint.sh

EXPOSE 8000

ENTRYPOINT ["./docker/test/docker-entrypoint.sh"]
